# --- Temel İşleyici (Backend) ---
# Nvidia ve Intel hibrit sistemler için GLX şarttır.
backend = "glx";
glx-copy-from-front = false;
use-damage = true;
vsync = true;

# --- Köşeleri Ovalleştirme (Corners) ---
corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# --- Gölgeler (Shadows) ---
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.5;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "_GTK_FRAME_EXTENTS@:c"
];

# --- Şeffaflık ve Karartma (Opacity) ---
active-opacity = 1.0;
inactive-opacity = 0.9;
frame-opacity = 1.0;
inactive-opacity-override = false;

# Kitty ve diğer pencereler için özel kurallar
opacity-rule = [
  "100:class_g = 'LibreWolf'",
  "100:class_g = 'Thunar'",
  "90:class_g = 'kitty' && !focused",
  "100:class_g = 'kitty' && focused"
];

# --- Bulanıklaştırma (Blur) ---
# Kitty'nin arkasının buzlu cam gibi görünmesini sağlar.
blur-method = "dual_kawase";
blur-strength = 5;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
];

# --- Geçiş Efektleri (Fading) ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

# --- Diğer Ayarlar ---
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
mark-wmwin-focused = true;
mark-ovlp-focused = true;
