#! /bin/sh
xinput set-prop 10 "libinput Accel Speed" -0.5 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config single_monocle true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc config focused_border_color "#022d5b"
bspc config normal_border_color "#000000"
bspc config active_border_color "#4a729e"
bspc config gapless_monocle "#429af7"

bspc rule -a copyq state=floating follow=on
bspc rule -a zen-browser desktop='^2'
bspc rule -a spotify desktop='^3'

dunst &
feh --bg-fill ~/wallpaper/music.png &
xsetroot -cursor_name left_ptr &
numlockx on &
copyq &
picom --animations &
xinput set-prop 10 "libinput Accel Speed" -0.5 &
