#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 35

bspc config split_ratio          0.5
bspc config single_monocle true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true



bspc config focused_border_color "#022d5b"
bspc config normal_border_color "#000000"
bspc config active_border_color "#4a729e"
bspc config gapless_monocle "#429af7"



bspc rule -a "librewolf" desktop='^2' follow=on
bspc rule -a "Spotify" desktop='^5' follow=on
bspc rule -a "kitty" desktop='^1' follow=on
bspc rule -a "obsidian" desktop='^3' follow=on
bspc rule -a "Thunar" desktop='^4' follow=on

bspc rule -a copyq state=floating follow=on
bspc rule -a "Blueman-manager" state=floating follow=on

bitwarden &
picom &
xset b off &
dunst &
feh --bg-fill ~/wallpaper/forest.png &
xsetroot -cursor_name left_ptr &
numlockx on &
copyq &
xinput set-prop 10 "libinput Accel Speed" -0.5 &
~/.config/polybar/launch.sh &
sleep 1 && xset r rate 200 35 &
nmapplet &
blueman-applet &
